### PR TITLE
0.28.1: Limit requirements to base package; add python_min

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
I took the liberty and already created a `0.x` branch from the last commit pre-1.0

**Comment by BastianZim** [comment]
Thanks @xhochy 

Would you like to co-maintain this package? If yes, please feel free to add yourself.

**Comment by xhochy** [comment]
> Thanks @xhochy 
> 
> 
> 
> Would you like to co-maintain this package? If yes, please feel free to add yourself.

No(t yet). I'm not using it directly but this showed up as a dependency of checkov. Having a whole analytics setup to check some Terraform definitions was a bit overkill.

**Comment by BastianZim** [comment]
Ok sounds good. Please feel free to add yourself whenever you would like to, no need to wait for me to merge the PR.

**Pull request merged**
